version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: weekly
    time: "04:00"
  open-pull-requests-limit: 10
  target-branch: dev
  reviewers:
  - pwnorbitals
  ignore:
  - dependency-name: y18n
    versions:
    - 4.0.1
  - dependency-name: express-rate-limit
    versions:
    - 5.2.3
    - 5.2.5
  - dependency-name: nodemailer
    versions:
    - 6.4.17
    - 6.4.18
  - dependency-name: joi
    versions:
    - 17.3.0
  - dependency-name: helmet
    versions:
    - 4.4.1
  - dependency-name: supertest
    versions:
    - 6.1.1
  - dependency-name: eslint
    versions:
    - 7.18.0
  - dependency-name: marked
    versions:
    - 1.2.7
