language: node_js
node_js:
- 13
services:
- redis-server

before_install:
- npm install pm2 -g

deploy:
  - provider: script
    script: pm2 deploy ecosystem.config.js production
    on: 
      branch: master 
  - provider: script
    script: pm2 deploy ecosystem.config.js staging
    on: 
      branch: staging 

